import type { Metadata } from "next";
import "./globals.css";
import Header from "@/sections/Header";
import Footer from "@/sections/Footer";


export const metadata: Metadata = {
  title: "Halir",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Header />
       {children}
      <Footer />
    </>
  );
}
