import type { Metadata } from "next";
import Header from "@/sections/Header";
import Footer from "@/sections/Footer";
import SmoothScroll from "@/components/providers/SmoothScroll";


export const metadata: Metadata = {
  title: "Halir",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
    <SmoothScroll>
      <Header />
       {children}
      <Footer />
    </SmoothScroll>
    </>
  );
}
